apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "guilhermemmnn/hello-go:v3"
          envFrom:
            - configMapRef:
                name: goserver-env    # Nome do metadata do arquivo configmap-env.yaml
#          env:
#            - name: NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env    # Nome do metadata do arquivo configmap-env.yaml
#                  key: NAME             # Nome da chave da variável do arquivo configmap-env.yaml
#            - name: AGE
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: AGE