apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "guilhermemmnn/hello-go:v5"
          envFrom:
            - configMapRef:             # Puxa todas as variáveis de ambiente do arquivo abaixo para nossa aplicação
                name: goserver-env      # Nome do metadata que esta no arquivo configmap-env.yaml

            - secretRef:                # Puxa todas as secrets do arquivo abaixo para nossa aplicação
                name: goserver-secret   # Nome do metadata que esta no arquivo secret.yaml

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"