apiVersion: networking.k8s.io/v1  # Necessário checar novas atualizações dessa api
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "ingress.fullcycle.com.br"
      http:
        paths:
          - pathType: Prefix
            path: "/"                     # Prefixo depois da URL para acessar o serviço abaixo
            backend:
              service:
                name: goserver-service    # Nome do serviço que será chamado ao acessar esse PATH
                port:
                  number: 80
