apiVersion: networking.k8s.io/v1  # Necessário checar novas atualizações dessa api
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"       # Comente caso não utilize o protocolo TLS
    ingress.kubernetes.io/force-ssl-redirect: "true"    # Caso o usuário acesse por http ele redireciona para https
spec:
  rules:
    - host: "ingress.fullcycle.com.br"
      http:
        paths:
          - pathType: Prefix
            path: "/"                     # Prefixo depois da URL para acessar o serviço abaixo
            backend:
              service:
                name: goserver-service    # Nome do serviço que será chamado ao acessar esse PATH
                port:
                  number: 80
  tls:
    - hosts:
      - "ingress.fullcycle.com.br"
      secretName: letsencrypt-tls
