apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
    - name: goserver
      image: "guilhermemmnn/hello-go:latest"      # O pod rodará essa imagem ( publicada no DockerHub )