apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver       # Vai pegar todos os pods que tiverem com o nome 'goserver'
  type: LoadBalancer
  ports:
    - port: 80          # Indica qual a porta da nossa service
      targetPort: 8000  # Indica qual a porta da nossa aplicação/pod
      protocol: TCP
